const crypto = require("node:crypto");

const PLAN_WINDOW_DAYS = 7;

function dateOffset(day, offset) {
  const date = new Date(`${day}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + offset);
  return date.toISOString().slice(0, 10);
}

function weekdayIndex(day) {
  const weekday = new Date(`${day}T12:00:00+08:00`).getDay();
  return weekday === 0 ? 6 : weekday - 1;
}

function weeklyCount(schedule, day) {
  const counts = Array.isArray(schedule.weeklyCounts) ? schedule.weeklyCounts : [];
  return Math.max(0, Math.min(12, Number(counts[weekdayIndex(day)]) || 0));
}

function scheduleIsActive(schedule, day) {
  return Boolean(
    schedule
    && typeof schedule.startDay === "string"
    && day >= schedule.startDay
    && (!schedule.endDay || day <= schedule.endDay),
  );
}

function courseIsActive(member, courseId, day) {
  if (!courseId || !day) return false;
  const schedules = Array.isArray(member?.courseSchedules) ? member.courseSchedules : [];
  return schedules.some((schedule) => (
    schedule?.courseId === courseId && scheduleIsActive(schedule, day)
  ));
}

function filterActiveCourseTasks(member, day, tasks) {
  if (!Array.isArray(tasks)) return [];
  return tasks.filter((task) => (
    task?.kind !== "course" || courseIsActive(member, task.courseId, day)
  ));
}

function slotsBeforeDay(schedule, day) {
  if (!scheduleIsActive(schedule, day) && day <= schedule.startDay) return 0;
  const endExclusive = schedule.endDay && schedule.endDay < day
    ? dateOffset(schedule.endDay, 1)
    : day;
  const totalDays = Math.max(0, Math.round(
    (new Date(`${endExclusive}T00:00:00Z`).getTime() - new Date(`${schedule.startDay}T00:00:00Z`).getTime())
      / (24 * 60 * 60 * 1000),
  ));
  const fullWeeks = Math.floor(totalDays / 7);
  const weeklyTotal = (Array.isArray(schedule.weeklyCounts) ? schedule.weeklyCounts : [])
    .reduce((sum, count) => sum + Math.max(0, Number(count) || 0), 0);
  let slots = fullWeeks * weeklyTotal;
  let cursor = dateOffset(schedule.startDay, fullWeeks * 7);
  for (let index = fullWeeks * 7; index < totalDays; index += 1) {
    slots += weeklyCount(schedule, cursor);
    cursor = dateOffset(cursor, 1);
  }
  return slots;
}

function shiftCountForDay(actions, scheduleId, day) {
  if (!Array.isArray(actions)) return 0;
  return actions.reduce((total, action) => (
    action?.mode === "shift"
      && action.scheduleId === scheduleId
      && typeof action.targetDay === "string"
      && action.targetDay <= day
      ? total + 1
      : total
  ), 0);
}

function unitLessonAt(schedule, absoluteIndex) {
  if (absoluteIndex < 0) return null;
  let offset = absoluteIndex;
  for (const unit of schedule.units || []) {
    const lessons = Math.max(0, Number(unit.lessons) || 0);
    if (offset < lessons) {
      return {
        key: `u${unit.unit}-l${offset + 1}`,
        unit: Number(unit.unit),
        lesson: offset + 1,
        label: `第${unit.unit}单元 · 第${offset + 1}课`,
      };
    }
    offset -= lessons;
  }
  return null;
}

function sequenceLessonAt(schedule, absoluteIndex) {
  if (absoluteIndex < 0) return null;
  const lesson = absoluteIndex + 1;
  const totalLessons = Number(schedule.totalLessons);
  if (Number.isFinite(totalLessons) && totalLessons > 0 && lesson > totalLessons) return null;
  return {
    key: `l${lesson}`,
    lesson,
    label: `第${lesson}课`,
  };
}

function lessonAt(schedule, relativeIndex) {
  const absoluteIndex = Math.max(0, Number(schedule.startIndex) || 0) + relativeIndex;
  return schedule.structure === "unit"
    ? unitLessonAt(schedule, absoluteIndex)
    : sequenceLessonAt(schedule, absoluteIndex);
}

function courseTaskId(courseId, lessonKey) {
  const digest = crypto.createHash("sha256").update(`${courseId}|${lessonKey}`).digest("hex");
  return `course-${digest.slice(0, 28)}`;
}

function taskForLesson(schedule, lesson) {
  const title = `${schedule.name}｜${lesson.label}`;
  return {
    id: courseTaskId(schedule.courseId, lesson.key),
    title,
    kind: "course",
    courseId: schedule.courseId,
    scheduleId: schedule.id,
    courseName: schedule.name,
    lessonKey: lesson.key,
    unit: Number.isFinite(lesson.unit) ? lesson.unit : undefined,
    lesson: lesson.lesson,
    autoGenerated: true,
  };
}

function tasksForScheduleDay(schedule, day, actions = []) {
  if (!scheduleIsActive(schedule, day)) return [];
  const count = weeklyCount(schedule, day);
  if (!count) return [];
  const baseSlot = slotsBeforeDay(schedule, day);
  const shifts = shiftCountForDay(actions, schedule.id, day);
  const tasks = [];
  for (let index = 0; index < count; index += 1) {
    const lesson = lessonAt(schedule, baseSlot + index - shifts);
    if (lesson) tasks.push(taskForLesson(schedule, lesson));
  }
  return tasks;
}

function generatedScheduleIds(member, day) {
  const value = member?.courseGeneratedDays?.[day];
  return new Set(Array.isArray(value) ? value.filter((id) => typeof id === "string") : []);
}

function courseTasksForDay(member, day, options = {}) {
  const generated = generatedScheduleIds(member, day);
  const includePaused = new Set(Array.isArray(options.includeScheduleIds) ? options.includeScheduleIds : []);
  const schedules = Array.isArray(member?.courseSchedules) ? member.courseSchedules : [];
  const actions = Array.isArray(member?.courseActions) ? member.courseActions : [];
  return schedules.flatMap((schedule) => {
    if (!scheduleIsActive(schedule, day)) return [];
    if (!schedule.autoContinue && !generated.has(schedule.id) && !includePaused.has(schedule.id)) return [];
    return tasksForScheduleDay(schedule, day, actions);
  });
}

function makeupTasksForDay(member, day) {
  const actions = Array.isArray(member?.courseActions) ? member.courseActions : [];
  return actions.flatMap((action) => {
    if (action?.mode !== "move" || action.targetDay !== day || !action.task) return [];
    return [{
      ...action.task,
      completed: undefined,
      makeupFromDay: action.sourceDay,
      autoGenerated: true,
    }];
  });
}

function mergeUniqueTasks(...lists) {
  const seen = new Set();
  const result = [];
  for (const list of lists) {
    for (const task of Array.isArray(list) ? list : []) {
      if (!task?.id || seen.has(task.id)) continue;
      seen.add(task.id);
      result.push(task);
    }
  }
  return result;
}

function combineDailyTasks(baseTasks, scheduledTasks, makeupTasks) {
  return mergeUniqueTasks(scheduledTasks, makeupTasks, baseTasks);
}

function fixedPlanDays(startDay) {
  return Array.from({ length: PLAN_WINDOW_DAYS }, (_, index) => dateOffset(startDay, index));
}

module.exports = {
  PLAN_WINDOW_DAYS,
  combineDailyTasks,
  courseIsActive,
  courseTaskId,
  courseTasksForDay,
  dateOffset,
  filterActiveCourseTasks,
  fixedPlanDays,
  lessonAt,
  makeupTasksForDay,
  mergeUniqueTasks,
  scheduleIsActive,
  slotsBeforeDay,
  tasksForScheduleDay,
  weekdayIndex,
  weeklyCount,
};
