const tcb = require("@cloudbase/node-sdk");
const crypto = require("node:crypto");
const {
  PLAN_WINDOW_DAYS,
  courseTasksForDay,
  dateOffset,
  fixedPlanDays,
  lessonAt,
  makeupTasksForDay,
  mergeUniqueTasks,
  scheduleIsActive,
  tasksForScheduleDay,
} = require("./course-plan");

const app = tcb.init({ env: tcb.SYMBOL_DEFAULT_ENV });
const db = app.database();
const command = db.command;

const GROUP_ID = "study-checkin-fixed-pair";
const FOCUS_PRESENCE_ID = `focus-presence-${GROUP_ID}`;
const STUDY_DAY_START_HOUR = 5;
const HOUR_MS = 60 * 60 * 1000;
const MAX_TASKS_PER_DAY = 12;
const MAX_COURSES = 6;
const MAX_COURSE_ACTIONS = 180;
const MEMBER_DEFINITIONS = [
  { id: "study-user-1", userKey: "user1", name: "蔡", color: "#4f6bf6" },
  { id: "study-user-2", userKey: "user2", name: "刘", color: "#7c5cfc" },
];
const DEFAULT_TASKS = {
  user1: [
    { id: "words-1", title: "英语单词学习 · 第 1 次" },
    { id: "words-2", title: "英语单词学习 · 第 2 次" },
    { id: "review", title: "英语单词复习" },
    { id: "computer-2", title: "计算机二级" },
    { id: "civil-service", title: "考公课程" },
  ],
  user2: [],
};

class PublicError extends Error {}

function success(data) {
  return { ok: true, data };
}

function failure(error) {
  const message = error instanceof PublicError ? error.message : "服务暂时不可用，请稍后再试";
  if (!(error instanceof PublicError)) console.error(error);
  return { ok: false, error: message };
}

function first(result) {
  if (!result || !result.data) return null;
  return Array.isArray(result.data) ? result.data[0] ?? null : result.data;
}

function hash(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function validDay(day) {
  return typeof day === "string" && /^\d{4}-\d{2}-\d{2}$/.test(day);
}

function dayInChina(date) {
  const studyDate = new Date(date.getTime() - STUDY_DAY_START_HOUR * HOUR_MS);
  const parts = new Intl.DateTimeFormat("zh-CN", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(studyDate);
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${values.year}-${values.month}-${values.day}`;
}

function cleanStoredTasks(tasks) {
  if (!Array.isArray(tasks)) return [];
  return tasks.slice(0, MAX_TASKS_PER_DAY).flatMap((task) => {
    const id = typeof task?.id === "string" ? task.id.trim() : "";
    const titleLimit = task?.kind === "course" ? 60 : 30;
    const title = typeof task?.title === "string" ? task.title.trim().slice(0, titleLimit) : "";
    if (!id || !title) return [];
    if (task.kind !== "course") return [{ id, title }];
    const courseId = typeof task.courseId === "string" ? task.courseId.trim().slice(0, 60) : "";
    const scheduleId = typeof task.scheduleId === "string" ? task.scheduleId.trim().slice(0, 60) : "";
    const lessonKey = typeof task.lessonKey === "string" ? task.lessonKey.trim().slice(0, 40) : "";
    if (!courseId || !scheduleId || !lessonKey) return [{ id, title }];
    const cleaned = {
      id,
      title,
      kind: "course",
      courseId,
      scheduleId,
      courseName: typeof task.courseName === "string" ? task.courseName.trim().slice(0, 20) : "",
      lessonKey,
      lesson: Math.max(1, Number(task.lesson) || 1),
      autoGenerated: task.autoGenerated !== false,
    };
    if (Number.isFinite(Number(task.unit))) cleaned.unit = Math.max(1, Number(task.unit));
    if (validDay(task.makeupFromDay)) cleaned.makeupFromDay = task.makeupFromDay;
    return [cleaned];
  });
}

function cleanTaskInput(tasks, existingTasks = []) {
  if (!Array.isArray(tasks)) throw new PublicError("任务列表格式不正确");
  const existingById = new Map(cleanStoredTasks(existingTasks).map((task) => [task.id, task]));
  const seen = new Set();
  const cleaned = [];
  for (const raw of tasks.slice(0, MAX_TASKS_PER_DAY)) {
    let id = typeof raw?.id === "string" && /^[a-zA-Z0-9_-]{1,40}$/.test(raw.id)
      ? raw.id
      : `custom-${crypto.randomBytes(6).toString("hex")}`;
    const existing = existingById.get(id);
    const title = typeof raw?.title === "string"
      ? raw.title.trim().slice(0, existing?.kind === "course" ? 60 : 30)
      : "";
    if (!title) continue;
    if (existing?.kind === "course" && existing.title !== title) {
      id = `custom-${crypto.randomBytes(6).toString("hex")}`;
    } else if (!existing && id.startsWith("course-")) {
      id = `custom-${crypto.randomBytes(6).toString("hex")}`;
    }
    while (seen.has(id)) id = `custom-${crypto.randomBytes(6).toString("hex")}`;
    seen.add(id);
    cleaned.push(existing?.kind === "course" && existing.title === title
      ? { ...existing, title }
      : { id, title });
  }
  return cleaned;
}

function taskTemplateFor(member) {
  if (Array.isArray(member.taskTemplate)) return cleanStoredTasks(member.taskTemplate);
  if (Array.isArray(member.recurringTasks)) return cleanStoredTasks(member.recurringTasks);
  return cleanStoredTasks(DEFAULT_TASKS[member.userKey] ?? []);
}

function baseTasksFor(member, day) {
  if (member.taskOverrides && Object.prototype.hasOwnProperty.call(member.taskOverrides, day)) {
    return cleanStoredTasks(member.taskOverrides[day]);
  }
  const templateSince = typeof member.taskTemplateSince === "string" ? member.taskTemplateSince : "";
  if (Array.isArray(member.taskTemplate) && (!templateSince || day >= templateSince)) {
    return cleanStoredTasks(member.taskTemplate);
  }
  const recurringSince = typeof member.recurringTasksSince === "string" ? member.recurringTasksSince : "";
  if (Array.isArray(member.recurringTasks) && (!recurringSince || day >= recurringSince)) {
    return cleanStoredTasks(member.recurringTasks);
  }
  return DEFAULT_TASKS[member.userKey] ?? [];
}

function tasksFor(member, day) {
  const manuallyOverridden = Boolean(
    member.taskOverrides && Object.prototype.hasOwnProperty.call(member.taskOverrides, day),
  );
  const scheduled = manuallyOverridden ? [] : courseTasksForDay(member, day);
  return mergeUniqueTasks(
    baseTasksFor(member, day),
    scheduled,
    makeupTasksForDay(member, day),
  ).slice(0, MAX_TASKS_PER_DAY);
}

function cleanWeeklyCounts(value) {
  if (!Array.isArray(value) || value.length !== 7) {
    throw new PublicError("请分别设置周一到周日的课程数量");
  }
  const counts = value.map((count) => {
    const parsed = Number(count);
    if (!Number.isInteger(parsed) || parsed < 0 || parsed > 6) {
      throw new PublicError("每天的课程数量应为 0 到 6 课");
    }
    return parsed;
  });
  if (!counts.some((count) => count > 0)) throw new PublicError("每周至少安排一课");
  return counts;
}

function cleanUnits(value) {
  if (!Array.isArray(value) || !value.length || value.length > 40) {
    throw new PublicError("请填写 1 到 40 个单元的课数");
  }
  const seen = new Set();
  let total = 0;
  const units = value.map((entry) => {
    const unit = Number(entry?.unit);
    const lessons = Number(entry?.lessons);
    if (!Number.isInteger(unit) || unit < 1 || unit > 999 || seen.has(unit)) {
      throw new PublicError("单元编号应为不重复的正整数");
    }
    if (!Number.isInteger(lessons) || lessons < 1 || lessons > 200) {
      throw new PublicError("每个单元应包含 1 到 200 课");
    }
    seen.add(unit);
    total += lessons;
    return { unit, lessons };
  });
  if (total > 2000) throw new PublicError("一门课程最多录入 2000 课");
  return units;
}

function unitStartIndex(units, nextUnit, nextLesson) {
  let offset = 0;
  for (const unit of units) {
    if (unit.unit === nextUnit) {
      if (!Number.isInteger(nextLesson) || nextLesson < 1 || nextLesson > unit.lessons) {
        throw new PublicError("下一课不在该单元的课程范围内");
      }
      return offset + nextLesson - 1;
    }
    offset += unit.lessons;
  }
  throw new PublicError("下一课所在单元不在课程目录中");
}

function cleanCourseScheduleInput(event, courseId, scheduleId) {
  const name = typeof event.name === "string" ? event.name.trim().slice(0, 20) : "";
  if (!name) throw new PublicError("请填写课程名称");
  const structure = event.structure === "unit" ? "unit" : event.structure === "sequence" ? "sequence" : "";
  if (!structure) throw new PublicError("请选择课程结构");
  const weeklyCounts = cleanWeeklyCounts(event.weeklyCounts);
  const startDay = event.effectiveDay;
  if (!validDay(startDay)) throw new PublicError("生效日期格式错误");

  const schedule = {
    id: scheduleId,
    courseId,
    name,
    structure,
    weeklyCounts,
    startDay,
    autoContinue: event.autoContinue !== false,
    createdAt: Date.now(),
  };

  if (structure === "unit") {
    const units = cleanUnits(event.units);
    const nextUnit = Number(event.nextUnit);
    const nextLesson = Number(event.nextLesson);
    schedule.units = units;
    schedule.startIndex = unitStartIndex(units, nextUnit, nextLesson);
  } else {
    const nextLesson = Number(event.nextLesson);
    const totalValue = event.totalLessons === "" || event.totalLessons === null || event.totalLessons === undefined
      ? null
      : Number(event.totalLessons);
    if (!Number.isInteger(nextLesson) || nextLesson < 1 || nextLesson > 100000) {
      throw new PublicError("下一课应为正整数");
    }
    if (totalValue !== null && (!Number.isInteger(totalValue) || totalValue < nextLesson || totalValue > 100000)) {
      throw new PublicError("总课数不能小于下一课");
    }
    schedule.totalLessons = totalValue;
    schedule.startIndex = nextLesson - 1;
  }
  return schedule;
}

function currentCourseSchedules(member, day) {
  const schedules = Array.isArray(member.courseSchedules) ? member.courseSchedules : [];
  const candidates = schedules
    .filter((schedule) => !schedule.endDay || schedule.endDay >= day)
    .sort((a, b) => String(b.startDay).localeCompare(String(a.startDay)));
  const seen = new Set();
  return candidates.filter((schedule) => {
    if (!schedule?.courseId || seen.has(schedule.courseId)) return false;
    seen.add(schedule.courseId);
    return true;
  }).sort((a, b) => String(a.name).localeCompare(String(b.name), "zh-CN"));
}

function firstUpcomingCourseTask(schedule, day, actions) {
  let cursor = day < schedule.startDay ? schedule.startDay : day;
  for (let index = 0; index < 21; index += 1) {
    if (schedule.endDay && cursor > schedule.endDay) return null;
    const task = tasksForScheduleDay(schedule, cursor, actions)[0];
    if (task) return task;
    cursor = dateOffset(cursor, 1);
  }
  return null;
}

function publicCourseTemplates(member, day) {
  const actions = Array.isArray(member.courseActions) ? member.courseActions : [];
  return currentCourseSchedules(member, day).map((schedule) => {
    const nextTask = firstUpcomingCourseTask(schedule, day, actions) || (() => {
      const lesson = lessonAt(schedule, 0);
      return lesson ? { unit: lesson.unit, lesson: lesson.lesson, title: `${schedule.name}｜${lesson.label}` } : null;
    })();
    return {
      courseId: schedule.courseId,
      scheduleId: schedule.id,
      name: schedule.name,
      structure: schedule.structure,
      units: schedule.structure === "unit" ? schedule.units : [],
      totalLessons: schedule.structure === "sequence" ? schedule.totalLessons ?? null : null,
      nextUnit: nextTask?.unit ?? null,
      nextLesson: nextTask?.lesson ?? null,
      nextLabel: nextTask?.title ?? "课程已完成",
      weeklyCounts: schedule.weeklyCounts,
      effectiveDay: schedule.startDay,
      autoContinue: schedule.autoContinue !== false,
    };
  });
}

function fullTaskCount(member, day) {
  const manuallyOverridden = Boolean(
    member.taskOverrides && Object.prototype.hasOwnProperty.call(member.taskOverrides, day),
  );
  return mergeUniqueTasks(
    baseTasksFor(member, day),
    manuallyOverridden ? [] : courseTasksForDay(member, day),
    makeupTasksForDay(member, day),
  ).length;
}

function assertCourseCapacity(member, startDay) {
  for (const day of fixedPlanDays(startDay)) {
    if (fullTaskCount(member, day) > MAX_TASKS_PER_DAY) {
      throw new PublicError(`${day} 的总任务会超过 ${MAX_TASKS_PER_DAY} 项，请减少当天课程数量`);
    }
  }
}

function focusStateId(memberId) {
  return `focus-state-${memberId}`;
}

function newSummaryRevision() {
  return `${Date.now().toString(36)}-${crypto.randomBytes(6).toString("hex")}`;
}

function publicFocusSession(session) {
  if (!session) return null;
  const timerMode = session.timerMode === "pomodoro" ? "pomodoro" : "stopwatch";
  const pausedAtValue = Number(session.pausedAt);
  const pausedAt = Number.isFinite(pausedAtValue) && pausedAtValue > 0 ? pausedAtValue : null;
  const pausedDurationMs = Math.max(0, Number(session.pausedDurationMs) || 0);
  const pomodoro = timerMode === "pomodoro" ? {
    focusMinutes: Math.max(1, Number(session.pomodoro?.focusMinutes) || 25),
    breakMinutes: Math.max(1, Number(session.pomodoro?.breakMinutes) || 5),
  } : null;
  return {
    id: session.id || session._id,
    memberId: session.memberId,
    day: session.day,
    taskId: session.taskId || null,
    taskTitle: session.taskTitle || "自由自习",
    startedAt: session.startedAt,
    timerMode,
    pomodoro,
    pausedAt,
    pausedDurationMs,
  };
}

function timerConfigFromEvent(event) {
  if (event.timerMode !== "pomodoro") return { timerMode: "stopwatch", pomodoro: null };
  const focusMinutes = Number(event.focusMinutes);
  const breakMinutes = Number(event.breakMinutes);
  if (!Number.isInteger(focusMinutes) || focusMinutes < 1 || focusMinutes > 180) {
    throw new PublicError("专注时长需设置为 1 到 180 分钟");
  }
  if (!Number.isInteger(breakMinutes) || breakMinutes < 1 || breakMinutes > 60) {
    throw new PublicError("休息时长需设置为 1 到 60 分钟");
  }
  return { timerMode: "pomodoro", pomodoro: { focusMinutes, breakMinutes } };
}

function totalPausedMilliseconds(session, endedAt) {
  const completedPause = Math.max(0, Number(session.pausedDurationMs) || 0);
  const currentPause = session.pausedAt
    ? Math.max(0, endedAt - Number(session.pausedAt))
    : 0;
  return completedPause + currentPause;
}

function activeElapsedSeconds(session, endedAt) {
  const wallMilliseconds = Math.max(0, endedAt - Number(session.startedAt));
  return Math.max(0, Math.floor((wallMilliseconds - totalPausedMilliseconds(session, endedAt)) / 1000));
}

function studyDurationSeconds(session, endedAt) {
  const activeSeconds = activeElapsedSeconds(session, endedAt);
  if (session.timerMode !== "pomodoro") return activeSeconds;
  const focusSeconds = Math.max(1, Number(session.pomodoro?.focusMinutes) || 25) * 60;
  const breakSeconds = Math.max(1, Number(session.pomodoro?.breakMinutes) || 5) * 60;
  const cycleSeconds = focusSeconds + breakSeconds;
  const fullCycles = Math.floor(activeSeconds / cycleSeconds);
  return fullCycles * focusSeconds + Math.min(activeSeconds % cycleSeconds, focusSeconds);
}

async function loadFocusState(member, day) {
  const collection = db.collection("sessions");
  const id = focusStateId(member.id);
  const existing = first(await collection.doc(id).get());
  if (existing) {
    const { _id, ...state } = existing;
    return state;
  }

  // One-time compatibility migration from the first self-study release.
  const [legacyActiveRow, legacyDailyRow] = await Promise.all([
    collection.doc(`focus-active-${member.id}`).get(),
    collection.doc(`focus-day-${member.id}-${day}`).get(),
  ]);
  const legacyActive = first(legacyActiveRow);
  const legacyDaily = first(legacyDailyRow);
  const state = {
    id,
    kind: "focus-state",
    groupId: GROUP_ID,
    memberId: member.id,
    active: publicFocusSession(legacyActive),
    days: legacyDaily ? { [day]: {
      totalSeconds: Math.max(0, Number(legacyDaily.totalSeconds) || 0),
      segments: Array.isArray(legacyDaily.segments) ? legacyDaily.segments : [],
    } } : {},
    updatedAt: Date.now(),
  };
  await collection.doc(id).set(state);
  return state;
}

async function loadFocusPresence(members, day, knownStates = null) {
  const collection = db.collection("sessions");
  const existing = first(await collection.doc(FOCUS_PRESENCE_ID).get());
  if (existing) {
    const { _id, ...presence } = existing;
    return presence;
  }

  const states = knownStates || await Promise.all(members.map((member) => loadFocusState(member, day)));
  const activeByMember = {};
  members.forEach((member, index) => {
    activeByMember[member.id] = publicFocusSession(states[index]?.active || null);
  });
  const presence = {
    id: FOCUS_PRESENCE_ID,
    kind: "focus-presence",
    groupId: GROUP_ID,
    activeByMember,
    summaryRevision: newSummaryRevision(),
    updatedAt: Date.now(),
  };
  await collection.doc(FOCUS_PRESENCE_ID).set(presence);
  return presence;
}

async function updateFocusPresence(memberId, session, summaryChanged = false) {
  const summaryRevision = summaryChanged ? newSummaryRevision() : null;
  const changes = {
    [`activeByMember.${memberId}`]: command.set(publicFocusSession(session)),
    updatedAt: Date.now(),
  };
  if (summaryRevision) changes.summaryRevision = summaryRevision;
  await db.collection("sessions").doc(FOCUS_PRESENCE_ID).update(changes);
  return summaryRevision;
}

async function markFocusSummaryChanged() {
  const summaryRevision = newSummaryRevision();
  await db.collection("sessions").doc(FOCUS_PRESENCE_ID).update({
    summaryRevision,
    updatedAt: Date.now(),
  });
  return summaryRevision;
}

async function readFocusSummary(members, day) {
  const states = await Promise.all(members.map((member) => loadFocusState(member, day)));
  const presence = await loadFocusPresence(members, day, states);
  const activeByMember = {};
  const todaySecondsByMember = {};
  const todayTaskSecondsByMember = {};

  members.forEach((member, index) => {
    const state = states[index];
    const active = publicFocusSession(presence.activeByMember?.[member.id] || null);
    const daily = state.days?.[day] || null;
    const segments = Array.isArray(daily?.segments) ? daily.segments : [];
    const taskSeconds = {};
    for (const segment of segments) {
      const key = segment.taskId || "free";
      taskSeconds[key] = (taskSeconds[key] || 0) + Math.max(0, Number(segment.durationSeconds) || 0);
    }
    activeByMember[member.id] = active;
    todaySecondsByMember[member.id] = Math.max(0, Number(daily?.totalSeconds) || 0);
    todayTaskSecondsByMember[member.id] = taskSeconds;
  });

  return {
    serverNow: Date.now(),
    summaryRevision: typeof presence.summaryRevision === "string" ? presence.summaryRevision : "",
    activeByMember,
    todaySecondsByMember,
    todayTaskSecondsByMember,
  };
}

async function ensureFixedSpace() {
  const groupCollection = db.collection("groups");
  const memberCollection = db.collection("members");
  let group = first(await groupCollection.doc(GROUP_ID).get());
  if (!group) {
    const createdAt = Date.now();
    await groupCollection.doc(GROUP_ID).set({
      id: GROUP_ID,
      mode: "fixed-pair",
      createdAt,
    });
    group = { id: GROUP_ID, mode: "fixed-pair", createdAt };
  }

  const members = [];
  for (const definition of MEMBER_DEFINITIONS) {
    let member = first(await memberCollection.doc(definition.id).get());
    if (!member) {
      member = {
        ...definition,
        groupId: GROUP_ID,
        createdAt: Date.now(),
        taskOverrides: {},
      };
      await memberCollection.doc(definition.id).set(member);
    } else if (member.name !== definition.name || member.color !== definition.color) {
      await memberCollection.doc(definition.id).update({
        name: definition.name,
        color: definition.color,
        updatedAt: Date.now(),
      });
      member = { ...member, name: definition.name, color: definition.color };
    }
    members.push(member);
  }
  return { group, members };
}

async function selectUser(event) {
  if (!MEMBER_DEFINITIONS.some((member) => member.userKey === event.userKey)) {
    throw new PublicError("请选择蔡或刘");
  }
  await ensureFixedSpace();
  return { token: event.userKey };
}

function requireIdentity(token) {
  const definition = MEMBER_DEFINITIONS.find((member) => member.userKey === token);
  if (!definition) throw new PublicError("请先选择用户身份");
  return definition;
}

async function readCurrentMember(token) {
  const definition = requireIdentity(token);
  const member = first(await db.collection("members").doc(definition.id).get());
  return member || { ...definition, groupId: GROUP_ID, taskOverrides: {} };
}

async function requireSession(token) {
  const definition = requireIdentity(token);
  const collection = db.collection("members");
  const rows = await Promise.all(MEMBER_DEFINITIONS.map((item) => collection.doc(item.id).get()));
  const members = MEMBER_DEFINITIONS.map((item, index) => (
    first(rows[index]) || { ...item, groupId: GROUP_ID, taskOverrides: {} }
  ));
  const member = members.find((item) => item.userKey === token);
  if (!member) throw new PublicError("没有找到当前用户");
  return { member: { ...member, ...definition }, group: { id: GROUP_ID }, members };
}

async function readCheckins(groupId, from, to = null) {
  const rows = [];
  let offset = 0;
  const dayRange = to ? command.gte(from).and(command.lte(to)) : command.gte(from);
  while (true) {
    const result = await db.collection("checkins")
      .where({ groupId, day: dayRange })
      .orderBy("day", "desc")
      .skip(offset)
      .limit(100)
      .get();
    const batch = result.data || [];
    rows.push(...batch);
    if (batch.length < 100) break;
    offset += batch.length;
  }
  return rows;
}

async function getData(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const current = await requireSession(event.token);
  const windowDays = fixedPlanDays(event.day);
  const overdueFromDay = dateOffset(event.day, -7);
  const windowToDay = windowDays[windowDays.length - 1];
  const [rows, focus] = await Promise.all([
    readCheckins(current.group.id, overdueFromDay, windowToDay),
    readFocusSummary(current.members, event.day),
  ]);
  const completedByDay = {};

  for (const row of rows) {
    const key = `${row.memberId}:${row.day}`;
    if (!completedByDay[key]) completedByDay[key] = [];
    completedByDay[key].push(row.taskId || row.task);
  }

  const members = current.members
    .sort((a, b) => String(a.userKey).localeCompare(String(b.userKey)))
    .map(({ id, userKey, name, color }) => ({ id, userKey, name, color }));
  const tasksByMember = {};
  const planByMember = {};
  for (const member of current.members) {
    planByMember[member.id] = windowDays.map((day) => {
      const completed = new Set(completedByDay[`${member.id}:${day}`] || []);
      return {
        day,
        tasks: tasksFor(member, day).map((task) => ({
          ...task,
          completed: completed.has(task.id),
        })),
      };
    });
    tasksByMember[member.id] = planByMember[member.id][0].tasks;
  }

  const handled = new Set((Array.isArray(current.member.courseActions) ? current.member.courseActions : [])
    .map((action) => action?.key)
    .filter(Boolean));
  const overdueTasks = [];
  for (let offset = -1; offset >= -7; offset -= 1) {
    const day = dateOffset(event.day, offset);
    const completed = new Set(completedByDay[`${current.member.id}:${day}`] || []);
    for (const task of tasksFor(current.member, day)) {
      const key = `${day}|${task.id}`;
      if (task.kind === "course" && !completed.has(task.id) && !handled.has(key)) {
        overdueTasks.push({ ...task, sourceDay: day });
      }
    }
  }

  return {
    me: members.find((member) => member.id === current.member.id),
    members,
    tasksByMember,
    planDays: planByMember[current.member.id],
    taskTemplate: taskTemplateFor(current.member).map((task) => ({ ...task, completed: false })),
    courseTemplates: publicCourseTemplates(current.member, event.day),
    overdueTasks: overdueTasks.slice(0, MAX_TASKS_PER_DAY),
    repeatDaily: Array.isArray(current.member.recurringTasks),
    focus,
  };
}

async function getStudyHistory(event) {
  if (!validDay(event.fromDay) || !validDay(event.toDay) || event.toDay < event.fromDay) {
    throw new PublicError("历史日期范围不正确");
  }
  if (typeof event.month !== "string" || !/^\d{4}-\d{2}$/.test(event.month)) {
    throw new PublicError("月份格式不正确");
  }

  const requestedDays = [];
  let day = event.fromDay;
  while (day <= event.toDay && requestedDays.length <= 42) {
    requestedDays.push(day);
    day = dateOffset(day, 1);
  }
  if (requestedDays.length !== 42 || requestedDays[requestedDays.length - 1] !== event.toDay) {
    throw new PublicError("历史日期范围过大");
  }

  const current = await requireSession(event.token);
  const [rows, state] = await Promise.all([
    readCheckins(current.group.id, event.fromDay, event.toDay),
    loadFocusState(current.member, event.toDay),
  ]);
  const completedByDay = {};
  for (const row of rows) {
    if (row.memberId !== current.member.id) continue;
    if (!completedByDay[row.day]) completedByDay[row.day] = [];
    completedByDay[row.day].push(row.taskId || row.task);
  }

  const storedHistory = state.history && typeof state.history === "object" ? state.history : {};
  const resultDays = {};
  let totalSeconds = 0;
  let studyDays = 0;
  let completedDays = 0;
  for (const requestedDay of requestedDays) {
    const tasks = tasksFor(current.member, requestedDay);
    const completedIds = new Set(completedByDay[requestedDay] || []);
    const completed = tasks.filter((task) => completedIds.has(task.id)).length;
    const seconds = Math.max(0, Number(storedHistory[requestedDay] ?? state.days?.[requestedDay]?.totalSeconds) || 0);
    const allDone = tasks.length > 0 && completed === tasks.length;
    resultDays[requestedDay] = { totalSeconds: seconds, completed, total: tasks.length, allDone };
    if (requestedDay.startsWith(event.month)) {
      totalSeconds += seconds;
      if (seconds > 0) studyDays += 1;
      if (allDone) completedDays += 1;
    }
  }

  return { days: resultDays, totalSeconds, studyDays, completedDays };
}

async function getFocusStatus(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  requireIdentity(event.token);
  const presence = await loadFocusPresence(MEMBER_DEFINITIONS, event.day);
  const activeByMember = {};
  for (const member of MEMBER_DEFINITIONS) {
    activeByMember[member.id] = publicFocusSession(presence.activeByMember?.[member.id] || null);
  }
  return {
    serverNow: Date.now(),
    summaryRevision: typeof presence.summaryRevision === "string" ? presence.summaryRevision : "",
    activeByMember,
  };
}

async function startFocus(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const definition = requireIdentity(event.token);
  const member = event.taskId ? await readCurrentMember(event.token) : definition;
  const presence = await loadFocusPresence(MEMBER_DEFINITIONS, event.day);
  if (presence.activeByMember?.[definition.id]) throw new PublicError("你已经在自习中了");

  let taskId = null;
  let taskTitle = "自由自习";
  if (event.taskId !== null && event.taskId !== undefined && event.taskId !== "") {
    if (typeof event.taskId !== "string") throw new PublicError("无效的自习任务");
    const task = tasksFor(member, event.day).find((item) => item.id === event.taskId);
    if (!task) throw new PublicError("这个任务已不存在，请刷新后重试");
    taskId = task.id;
    taskTitle = task.title;
  }

  const timer = timerConfigFromEvent(event);
  const session = {
    id: `focus-active-${definition.id}`,
    kind: "focus-active",
    groupId: GROUP_ID,
    memberId: definition.id,
    day: event.day,
    taskId,
    taskTitle,
    startedAt: Date.now(),
    timerMode: timer.timerMode,
    pomodoro: timer.pomodoro,
    pausedAt: null,
    pausedDurationMs: 0,
  };
  await updateFocusPresence(definition.id, session);
  return { session: publicFocusSession(session) };
}

async function setFocusPaused(event) {
  if (typeof event.paused !== "boolean") throw new PublicError("暂停状态不正确");
  const definition = requireIdentity(event.token);
  const presence = await loadFocusPresence(MEMBER_DEFINITIONS, dayInChina(new Date()));
  const active = publicFocusSession(presence.activeByMember?.[definition.id] || null);
  if (!active) throw new PublicError("当前没有进行中的自习");

  const alreadyPaused = Boolean(active.pausedAt);
  if (alreadyPaused === event.paused) return { session: active };

  const changedAt = Date.now();
  const session = {
    ...active,
    pausedAt: event.paused ? changedAt : null,
    pausedDurationMs: event.paused
      ? active.pausedDurationMs
      : active.pausedDurationMs + Math.max(0, changedAt - Number(active.pausedAt)),
  };
  await updateFocusPresence(definition.id, session);
  return { session: publicFocusSession(session) };
}

async function stopFocus(event) {
  const definition = requireIdentity(event.token);
  const collection = db.collection("sessions");
  const presence = await loadFocusPresence(MEMBER_DEFINITIONS, dayInChina(new Date()));
  const active = publicFocusSession(presence.activeByMember?.[definition.id] || null);
  if (!active) throw new PublicError("当前没有进行中的自习");
  const state = await loadFocusState(definition, dayInChina(new Date()));

  const endedAt = Date.now();
  const wallDurationSeconds = Math.max(0, Math.floor((endedAt - Number(active.startedAt)) / 1000));
  const pausedDurationSeconds = Math.floor(totalPausedMilliseconds(active, endedAt) / 1000);
  const durationSeconds = studyDurationSeconds(active, endedAt);
  const sessionId = `focus-${hash(`${definition.id}|${active.startedAt}`).slice(0, 34)}`;
  const completed = {
    id: sessionId,
    kind: "focus-session",
    status: "completed",
    groupId: GROUP_ID,
    memberId: definition.id,
    day: active.day,
    taskId: active.taskId || null,
    taskTitle: active.taskTitle || "自由自习",
    startedAt: Number(active.startedAt),
    endedAt,
    durationSeconds,
    wallDurationSeconds,
    pausedDurationSeconds,
    timerMode: active.timerMode,
    pomodoro: active.pomodoro,
  };

  await collection.doc(sessionId).set(completed);
  const daily = state.days?.[active.day] || null;
  const segments = Array.isArray(daily?.segments) ? daily.segments : [];
  const alreadyRecorded = segments.some((segment) => segment.id === sessionId);
  const nextSegments = alreadyRecorded ? segments : [...segments, {
    id: sessionId,
    taskId: completed.taskId,
    taskTitle: completed.taskTitle,
    startedAt: completed.startedAt,
    endedAt,
    durationSeconds,
    wallDurationSeconds,
    pausedDurationSeconds,
    timerMode: completed.timerMode,
    pomodoro: completed.pomodoro,
  }];
  const days = { ...(state.days || {}), [active.day]: {
    totalSeconds: nextSegments.reduce((sum, segment) => sum + Math.max(0, Number(segment.durationSeconds) || 0), 0),
    segments: nextSegments,
  } };
  const history = { ...(state.history || {}) };
  for (const [historyDay, value] of Object.entries(state.days || {})) {
    if (!Object.prototype.hasOwnProperty.call(history, historyDay)) {
      history[historyDay] = Math.max(0, Number(value?.totalSeconds) || 0);
    }
  }
  history[active.day] = days[active.day].totalSeconds;
  for (const oldDay of Object.keys(history).sort().reverse().slice(730)) delete history[oldDay];
  for (const oldDay of Object.keys(days).sort().reverse().slice(60)) delete days[oldDay];
  await collection.doc(focusStateId(definition.id)).set({
    ...state,
    active: null,
    days,
    history,
    updatedAt: endedAt,
  });
  const summaryRevision = await updateFocusPresence(definition.id, null, true);

  return {
    sessionId,
    day: active.day,
    taskId: completed.taskId,
    taskTitle: completed.taskTitle,
    durationSeconds,
    wallDurationSeconds,
    pausedDurationSeconds,
    timerMode: completed.timerMode,
    summaryRevision,
  };
}

async function toggleCheckin(event) {
  if (!validDay(event.day) || typeof event.taskId !== "string") {
    throw new PublicError("无效的打卡任务");
  }
  const member = await readCurrentMember(event.token);
  const task = tasksFor(member, event.day).find((item) => item.id === event.taskId);
  if (!task) throw new PublicError("这个任务已不存在，请刷新后重试");

  const id = hash(`${member.id}|${event.day}|${task.id}`).slice(0, 40);
  const collection = db.collection("checkins");
  const existing = first(await collection.doc(id).get());
  if (existing) {
    await collection.doc(id).remove();
    await markFocusSummaryChanged();
    return { completed: false };
  }

  await collection.doc(id).set({
    id,
    groupId: GROUP_ID,
    memberId: member.id,
    day: event.day,
    taskId: task.id,
    task: task.title,
    completedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { completed: true };
}

function requirePlanningWindow(event) {
  if (!validDay(event.day) || !validDay(event.effectiveDay)) {
    throw new PublicError("日期格式错误");
  }
  const lastDay = dateOffset(event.day, PLAN_WINDOW_DAYS - 1);
  if (event.effectiveDay < event.day || event.effectiveDay > lastDay) {
    throw new PublicError("生效日期必须在当前7天计划内");
  }
}

async function assertCourseDayMutable(member, courseId, day) {
  const courseIds = new Set(tasksFor(member, day)
    .filter((task) => task.kind === "course" && task.courseId === courseId)
    .map((task) => task.id));
  if (!courseIds.size) return;
  const [rows, presence] = await Promise.all([
    db.collection("checkins").where({ groupId: GROUP_ID, day }).limit(100).get(),
    loadFocusPresence(MEMBER_DEFINITIONS, day),
  ]);
  const completed = (rows.data || []).some((row) => (
    row.memberId === member.id && courseIds.has(row.taskId || row.task)
  ));
  const activeTaskId = presence.activeByMember?.[member.id]?.taskId;
  if (completed || courseIds.has(activeTaskId)) {
    throw new PublicError("这一天已有该课程的完成记录或正在自习，请改为从下一天生效");
  }
}

async function saveCourseTemplate(event) {
  requirePlanningWindow(event);
  const member = await readCurrentMember(event.token);
  const existingSchedules = Array.isArray(member.courseSchedules) ? member.courseSchedules : [];
  const requestedCourseId = typeof event.courseId === "string" ? event.courseId : "";
  const existingCourse = requestedCourseId
    ? existingSchedules.some((schedule) => schedule.courseId === requestedCourseId)
    : false;
  if (requestedCourseId && !existingCourse) throw new PublicError("课程模板已不存在，请刷新后重试");

  const activeCourseIds = new Set(currentCourseSchedules(member, event.day).map((schedule) => schedule.courseId));
  if (!existingCourse && activeCourseIds.size >= MAX_COURSES) {
    throw new PublicError(`每人最多设置 ${MAX_COURSES} 门自动课程`);
  }
  if (member.taskOverrides && Object.prototype.hasOwnProperty.call(member.taskOverrides, event.effectiveDay)) {
    throw new PublicError("该日期已手动修改任务，请选择另一个生效日期");
  }

  const courseId = existingCourse ? requestedCourseId : `course-${crypto.randomBytes(8).toString("hex")}`;
  if (existingCourse && event.effectiveDay === event.day) {
    await assertCourseDayMutable(member, courseId, event.effectiveDay);
  }
  const scheduleId = `schedule-${crypto.randomBytes(8).toString("hex")}`;
  const schedule = cleanCourseScheduleInput(event, courseId, scheduleId);
  const previousDay = dateOffset(event.effectiveDay, -1);
  const nextSchedules = existingSchedules.flatMap((item) => {
    if (item.courseId !== courseId) return [item];
    if (item.startDay >= event.effectiveDay) return [];
    if (!item.endDay || item.endDay >= event.effectiveDay) return [{ ...item, endDay: previousDay }];
    return [item];
  });
  nextSchedules.push(schedule);
  const candidate = { ...member, courseSchedules: nextSchedules };
  assertCourseCapacity(candidate, event.day);

  await db.collection("members").doc(member.id).update({
    courseSchedules: nextSchedules,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { courseId, scheduleId, planDays: fixedPlanDays(event.day) };
}

async function deleteCourseTemplate(event) {
  requirePlanningWindow(event);
  const member = await readCurrentMember(event.token);
  const courseId = typeof event.courseId === "string" ? event.courseId : "";
  const schedules = Array.isArray(member.courseSchedules) ? member.courseSchedules : [];
  if (!courseId || !schedules.some((schedule) => schedule.courseId === courseId)) {
    throw new PublicError("课程模板已不存在，请刷新后重试");
  }
  if (event.effectiveDay === event.day) await assertCourseDayMutable(member, courseId, event.effectiveDay);
  const previousDay = dateOffset(event.effectiveDay, -1);
  const nextSchedules = schedules.flatMap((schedule) => {
    if (schedule.courseId !== courseId) return [schedule];
    if (schedule.startDay >= event.effectiveDay) return [];
    if (!schedule.endDay || schedule.endDay >= event.effectiveDay) return [{ ...schedule, endDay: previousDay }];
    return [schedule];
  });
  await db.collection("members").doc(member.id).update({
    courseSchedules: nextSchedules,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { removed: true };
}

async function generateCourseWindow(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const member = await readCurrentMember(event.token);
  const scheduleId = typeof event.scheduleId === "string" ? event.scheduleId : "";
  const schedule = (Array.isArray(member.courseSchedules) ? member.courseSchedules : [])
    .find((item) => item.id === scheduleId);
  if (!schedule) throw new PublicError("课程模板已不存在，请刷新后重试");
  const generatedDays = { ...(member.courseGeneratedDays || {}) };
  const days = fixedPlanDays(event.day);
  for (const day of days) {
    if (!scheduleIsActive(schedule, day)) continue;
    generatedDays[day] = Array.from(new Set([
      ...(Array.isArray(generatedDays[day]) ? generatedDays[day] : []),
      schedule.id,
    ])).slice(0, MAX_COURSES);
  }
  const oldestKeptDay = dateOffset(event.day, -60);
  for (const day of Object.keys(generatedDays)) {
    if (!validDay(day) || day < oldestKeptDay) delete generatedDays[day];
  }
  const candidate = { ...member, courseGeneratedDays: generatedDays };
  assertCourseCapacity(candidate, event.day);
  await db.collection("members").doc(member.id).update({
    courseGeneratedDays: generatedDays,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { generated: days.length, planDays: days };
}

async function deferCourseTask(event) {
  if (!validDay(event.day) || !validDay(event.sourceDay) || event.sourceDay >= event.day) {
    throw new PublicError("待补任务日期不正确");
  }
  if (event.sourceDay < dateOffset(event.day, -7)) throw new PublicError("只能处理最近7天的待补课程");
  if (event.mode !== "move" && event.mode !== "shift") throw new PublicError("顺延方式不正确");
  if (typeof event.taskId !== "string") throw new PublicError("待补任务不正确");

  const member = await readCurrentMember(event.token);
  const key = `${event.sourceDay}|${event.taskId}`;
  const actions = Array.isArray(member.courseActions) ? member.courseActions : [];
  const existing = actions.find((action) => action?.key === key);
  if (existing) return { handled: true, mode: existing.mode };

  const task = tasksFor(member, event.sourceDay).find((item) => (
    item.id === event.taskId && item.kind === "course"
  ));
  if (!task) throw new PublicError("待补课程已发生变化，请刷新后重试");
  const checkinId = hash(`${member.id}|${event.sourceDay}|${task.id}`).slice(0, 40);
  if (first(await db.collection("checkins").doc(checkinId).get())) {
    throw new PublicError("这项课程已经完成，无需顺延");
  }

  if (event.mode === "move") {
    const todayTasks = tasksFor(member, event.day);
    if (!todayTasks.some((item) => item.id === task.id) && todayTasks.length >= MAX_TASKS_PER_DAY) {
      throw new PublicError(`今天已有 ${MAX_TASKS_PER_DAY} 项任务，无法继续移入`);
    }
  } else {
    if (member.taskOverrides && Object.prototype.hasOwnProperty.call(member.taskOverrides, event.day)) {
      throw new PublicError("今天的任务已手动修改，请使用“仅移到今天”");
    }
    const schedule = (Array.isArray(member.courseSchedules) ? member.courseSchedules : [])
      .find((item) => item.id === task.scheduleId);
    if (!schedule || !scheduleIsActive(schedule, event.day)) {
      throw new PublicError("原课程计划已结束或已改版，请使用“仅移到今天”");
    }
    await assertCourseDayMutable(member, task.courseId, event.day);
  }

  const taskSnapshot = cleanStoredTasks([task])[0];
  const action = {
    key,
    mode: event.mode,
    sourceDay: event.sourceDay,
    targetDay: event.day,
    taskId: task.id,
    courseId: task.courseId,
    scheduleId: task.scheduleId,
    task: taskSnapshot,
    createdAt: Date.now(),
  };
  const nextActions = [...actions, action]
    .sort((a, b) => Number(a.createdAt) - Number(b.createdAt))
    .slice(-MAX_COURSE_ACTIONS);
  const candidate = { ...member, courseActions: nextActions };
  assertCourseCapacity(candidate, event.day);
  await db.collection("members").doc(member.id).update({
    courseActions: nextActions,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { handled: true, mode: event.mode };
}

async function saveTasks(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const member = await readCurrentMember(event.token);
  const existingTasks = tasksFor(member, event.day);
  const tasks = cleanTaskInput(event.tasks, existingTasks);
  const overrides = { ...(member.taskOverrides || {}) };
  overrides[event.day] = tasks;
  const days = Object.keys(overrides).sort().reverse();
  for (const oldDay of days.slice(60)) delete overrides[oldDay];

  const nextIds = new Set(tasks.map((task) => task.id));
  const removedIds = new Set(existingTasks.filter((task) => !nextIds.has(task.id)).map((task) => task.id));
  if (removedIds.size) {
    const [rows, presence, focusState] = await Promise.all([
      db.collection("checkins").where({ groupId: GROUP_ID, day: event.day }).limit(100).get(),
      loadFocusPresence(MEMBER_DEFINITIONS, event.day),
      loadFocusState(member, event.day),
    ]);
    const hasCompleted = (rows.data || []).some((row) => (
      row.memberId === member.id && removedIds.has(row.taskId || row.task)
    ));
    const hasStudyRecord = (focusState.days?.[event.day]?.segments || []).some((segment) => (
      removedIds.has(segment.taskId)
    ));
    const active = presence.activeByMember?.[member.id] || null;
    if (hasCompleted || hasStudyRecord || (active?.day === event.day && removedIds.has(active.taskId))) {
      throw new PublicError("已有打卡或学习记录的任务不能删除，请先保留该任务");
    }
  }

  await db.collection("members").doc(member.id).update({
    taskOverrides: overrides,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { tasks };
}

async function saveTaskTemplate(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const member = await readCurrentMember(event.token);
  const template = cleanTaskInput(event.tasks, taskTemplateFor(member))
    .filter((task) => task.kind !== "course");

  // Saving the reusable template must not silently rewrite the visible 7-day plan.
  // Snapshot only dates that were still automatic; explicit day edits stay untouched.
  const overrides = { ...(member.taskOverrides || {}) };
  for (const day of fixedPlanDays(event.day)) {
    if (!Object.prototype.hasOwnProperty.call(overrides, day)) {
      overrides[day] = tasksFor(member, day);
    }
  }
  for (const oldDay of Object.keys(overrides).sort().reverse().slice(60)) delete overrides[oldDay];

  await db.collection("members").doc(member.id).update({
    taskTemplate: template,
    taskTemplateSince: event.day,
    taskOverrides: overrides,
    updatedAt: Date.now(),
  });
  await markFocusSummaryChanged();
  return { template };
}

async function applyTaskTemplate(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  if (event.scope !== "today" && event.scope !== "window") {
    throw new PublicError("模板应用范围不正确");
  }
  const member = await readCurrentMember(event.token);
  const targetDays = event.scope === "today" ? [event.day] : fixedPlanDays(event.day);
  const overrides = { ...(member.taskOverrides || {}) };
  const candidates = targetDays.map((day) => {
    const currentTasks = tasksFor(member, day);
    const candidateMember = { ...member, taskOverrides: { ...overrides, [day]: undefined } };
    delete candidateMember.taskOverrides[day];
    const nextTasks = tasksFor(candidateMember, day);
    const nextIds = new Set(nextTasks.map((task) => task.id));
    return {
      day,
      removedIds: new Set(currentTasks.filter((task) => !nextIds.has(task.id)).map((task) => task.id)),
    };
  });
  const hasPossibleRemoval = candidates.some((candidate) => candidate.removedIds.size > 0);
  const protectedDays = new Set();

  if (hasPossibleRemoval) {
    const [rows, presence, focusState] = await Promise.all([
      readCheckins(GROUP_ID, targetDays[0], targetDays[targetDays.length - 1]),
      loadFocusPresence(MEMBER_DEFINITIONS, event.day),
      loadFocusState(member, event.day),
    ]);
    for (const candidate of candidates) {
      if (!candidate.removedIds.size) continue;
      const completed = rows.some((row) => (
        row.memberId === member.id
        && row.day === candidate.day
        && candidate.removedIds.has(row.taskId || row.task)
      ));
      const studied = (focusState.days?.[candidate.day]?.segments || []).some((segment) => (
        candidate.removedIds.has(segment.taskId)
      ));
      const active = presence.activeByMember?.[member.id] || null;
      if (completed || studied || (active?.day === candidate.day && candidate.removedIds.has(active.taskId))) {
        protectedDays.add(candidate.day);
      }
    }
  }

  const appliedDays = [];
  for (const day of targetDays) {
    if (protectedDays.has(day)) continue;
    delete overrides[day];
    appliedDays.push(day);
  }
  if (appliedDays.length) {
    const update = { updatedAt: Date.now() };
    for (const day of appliedDays) {
      update[`taskOverrides.${day}`] = command.remove();
    }
    await db.collection("members").doc(member.id).update(update);
    await markFocusSummaryChanged();
  }
  return { appliedDays, skippedDays: Array.from(protectedDays) };
}

async function resetTasks(event) {
  if (!validDay(event.day)) throw new PublicError("日期格式错误");
  const member = await readCurrentMember(event.token);
  const update = {
    [`taskOverrides.${event.day}`]: command.remove(),
    updatedAt: Date.now(),
  };
  if (event.resetRecurring !== false) {
    update.recurringTasks = command.remove();
    update.recurringTasksSince = command.remove();
  }
  await db.collection("members").doc(member.id).update(update);

  const rows = await db.collection("checkins")
    .where({ groupId: GROUP_ID, day: event.day })
    .limit(100)
    .get();
  await Promise.all((rows.data || []).filter((row) => row.memberId === member.id).map((row) => (
    db.collection("checkins").doc(row._id || row.id).remove()
  )));
  await markFocusSummaryChanged();
  return { reset: true };
}

exports.main = async (event) => {
  try {
    switch (event.action) {
      case "selectUser":
        return success(await selectUser(event));
      case "getData":
        return success(await getData(event));
      case "getStudyHistory":
        return success(await getStudyHistory(event));
      case "getFocusStatus":
        return success(await getFocusStatus(event));
      case "toggleCheckin":
        return success(await toggleCheckin(event));
      case "saveCourseTemplate":
        return success(await saveCourseTemplate(event));
      case "deleteCourseTemplate":
        return success(await deleteCourseTemplate(event));
      case "generateCourseWindow":
        return success(await generateCourseWindow(event));
      case "deferCourseTask":
        return success(await deferCourseTask(event));
      case "saveTasks":
        return success(await saveTasks(event));
      case "saveTaskTemplate":
        return success(await saveTaskTemplate(event));
      case "applyTaskTemplate":
        return success(await applyTaskTemplate(event));
      case "resetTasks":
        return success(await resetTasks(event));
      case "startFocus":
        return success(await startFocus(event));
      case "setFocusPaused":
        return success(await setFocusPaused(event));
      case "stopFocus":
        return success(await stopFocus(event));
      default:
        throw new PublicError("未知操作");
    }
  } catch (error) {
    return failure(error);
  }
};
